//auth
export const SIGN_USER_IN_ACTION = "SIGN_USER_IN_ACTION";
export const LOG_USER_OUT_ACTION = "LOG_USER_OUT_ACTION";

//firstTime user
export const SET_FIRST_TIME_USER_ACTION = "SET_FIRST_TIME_USER_ACTION";
